number_of_points: 1024
number_of_classes: 40
learning_rate: 0.001
batch_size: 2
epochs: 30
random_seed: 42
data_dir: '../data/ModelNet40'
patience: 10
trials: 5
network:
  learning_rate: 0.001
hpo:
  enabled: False
  dropout1: [0.1, 0.2, 0.3, 0.4, 0.5]
  dropout2: [0.1, 0.2, 0.3, 0.4, 0.5]
  activation: ['relu', 'swish']
  batch_size: [32, 64, 128, 256, 512]