number_of_points: 2048
number_of_classes: 10
batch_size: 32
epochs: 20
random_seed: 42
data_dir: '../data/ModelNet10'
network:
  learning_rate: 0.001

hpo:
  dropout1: [0.1, 0.2, 0.3, 0.4, 0.5]
  dropout2: [0.1, 0.2, 0.3, 0.4, 0.5]
  activation: ['relu', 'leaky relu', 'swish']
  batch_size: [32, 64, 128, 256, 512]